package clase;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Graciela
 */
public class MainCarrera extends javax.swing.JFrame {

    private CaballosHilo caballo1, caballo2, caballo3;
    private int terminado = 0;

    private String nombre1;
    private String nombre2;
    private String nombre3;

    private boolean carreraCurso = false;

    /**
     * Creates new form MainCarrera
     */
    public MainCarrera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        pgb1 = new javax.swing.JProgressBar();
        pgb2 = new javax.swing.JProgressBar();
        pgb3 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        lblCaballo2 = new javax.swing.JLabel();
        lblCaballo3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAResultados = new javax.swing.JTextArea();
        bntStart = new javax.swing.JButton();
        lblCaballo1 = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        lblMeta = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblCaballo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cab2.png"))); // NOI18N
        lblCaballo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCaballo2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblCaballo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cab3.png"))); // NOI18N
        lblCaballo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCaballo3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        txtAResultados.setEditable(false);
        txtAResultados.setColumns(20);
        txtAResultados.setRows(5);
        jScrollPane1.setViewportView(txtAResultados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        bntStart.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        bntStart.setText("Start");
        bntStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntStartActionPerformed(evt);
            }
        });

        lblCaballo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caba1.png"))); // NOI18N
        lblCaballo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCaballo1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnNew.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        lblMeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vertical.png"))); // NOI18N
        lblMeta.setText("jLabel2");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bandera.png"))); // NOI18N

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCaballo2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCaballo1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pgb3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblCaballo3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pgb1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pgb2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMeta, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(bntStart, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(179, 179, 179))
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lblCaballo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pgb1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCaballo2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pgb2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCaballo3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pgb3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnNew)
                                    .addComponent(bntStart))
                                .addGap(11, 11, 11)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblMeta, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        terminado = 0;

        lblCaballo1.setLocation(10, lblCaballo1.getY());
        lblCaballo2.setLocation(10, lblCaballo2.getY());
        lblCaballo3.setLocation(10, lblCaballo3.getY());

        lblCaballo1.setText("");
        lblCaballo2.setText("");
        lblCaballo3.setText("");

        lblCaballo1.setLocation(10, lblCaballo1.getY());
        lblCaballo2.setLocation(10, lblCaballo2.getY());
        lblCaballo3.setLocation(10, lblCaballo3.getY());

        lblCaballo1.setText("");
        lblCaballo2.setText("");
        lblCaballo3.setText("");

        pgb1.setValue(0);
        pgb2.setValue(0);
        pgb3.setValue(0);

        txtAResultados.setText("");
    }//GEN-LAST:event_btnNewActionPerformed

    private void bntStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntStartActionPerformed

        nombre1 = JOptionPane.showInputDialog(this, "Ingrese el nombre del Caballo 1");
        nombre2 = JOptionPane.showInputDialog(this, "Ingrese el nombre del Caballo 2");
        nombre3 = JOptionPane.showInputDialog(this, "Ingrese el nombre del Caballo 3");

        if (nombre1 == null || nombre2 == null || nombre3 == null
                || nombre1.trim().equals("") || nombre2.trim().equals("") || nombre3.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar los 3 nombres");
            return;
        }

        terminado = 0;
        int inicio = 10;
        int meta = lblMeta.getX() - lblCaballo1.getWidth();

        lblCaballo1.setText(nombre1);
        lblCaballo2.setText(nombre2);
        lblCaballo3.setText(nombre3);

        lblCaballo1.setLocation(10, lblCaballo1.getY());
        lblCaballo2.setLocation(10, lblCaballo2.getY());
        lblCaballo3.setLocation(10, lblCaballo3.getY());

        lblCaballo1.setText(nombre1);
        lblCaballo2.setText(nombre2);
        lblCaballo3.setText(nombre3);

        lblCaballo1.setLocation(inicio, lblCaballo1.getY());
        lblCaballo2.setLocation(inicio, lblCaballo2.getY());
        lblCaballo3.setLocation(inicio, lblCaballo3.getY());

        //CReacion de los Hilos
        caballo1 = new CaballosHilo(nombre1, lblCaballo1, pgb1, inicio, this, meta);
        caballo2 = new CaballosHilo(nombre2, lblCaballo2, pgb2, inicio, this, meta);
        caballo3 = new CaballosHilo(nombre3, lblCaballo3, pgb3, inicio, this, meta);

        caballo1.start();
        caballo2.start();
        caballo3.start();

    }

    public synchronized void caballoTermino() {
        terminado++;

        if (terminado == 3) {
            long menor = caballo1.getTime();
            if (caballo2.getTime() < menor) {
                menor = caballo2.getTime();
            }
            if (caballo3.getTime() < menor) {
                menor = caballo3.getTime();
            }

            int cuantos = 0;
            String ganadores = "";
            if (caballo1.getTime() == menor) {
                ganadores = ganadores + caballo1.getNombre() + " ";
                cuantos++;
            }
            if (caballo2.getTime() == menor) {
                ganadores = ganadores + caballo2.getNombre() + " ";
                cuantos++;
            }
            if (caballo3.getTime() == menor) {
                ganadores = ganadores + caballo3.getNombre() + " ";
                cuantos++;
            }

            String texto = "";
            if (cuantos == 1) {
                texto = "GANADOR:\n" + ganadores + "\n";
            } else {
                texto = "EMPATE entre:\n" + ganadores + "\n";
            }

            texto = texto + "\nTIEMPOS:\n";
            texto = texto + caballo1.getNombre() + ": " + caballo1.getTime() + " ms\n";
            texto = texto + caballo2.getNombre() + ": " + caballo2.getTime() + " ms\n";
            texto = texto + caballo3.getNombre() + ": " + caballo3.getTime() + " ms\n";

            ImageIcon iconoTrofeo = new ImageIcon(getClass().getResource("/img/trofeo.png"));
            JOptionPane.showOptionDialog(this,texto, "Resultado de la Carrera",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, iconoTrofeo, new Object[]{"Aceptar"},"Aceptar");
                  
            
            txtAResultados.setText(texto);

        }


    }//GEN-LAST:event_bntStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainCarrera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel;
    private javax.swing.JButton bntStart;
    private javax.swing.JButton btnNew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCaballo1;
    private javax.swing.JLabel lblCaballo2;
    private javax.swing.JLabel lblCaballo3;
    private javax.swing.JLabel lblMeta;
    private javax.swing.JProgressBar pgb1;
    private javax.swing.JProgressBar pgb2;
    private javax.swing.JProgressBar pgb3;
    private javax.swing.JTextArea txtAResultados;
    // End of variables declaration//GEN-END:variables
}
